// Generated by tools/generate_page_assets.py from atlas_host.host_assets.
// Edit the catalogue, regenerate, and run the existing checks.

pub(crate) const VIEWER_SCRIPTS: [&[u8]; 9] = [
    include_bytes!("../web/vendor/openseadragon.min.js"),
    b"\n;\n",
    include_bytes!("../web/atlas-tools.js"),
    b"\n;\n",
    include_bytes!("../web/app.js"),
    b"\n;\n",
    include_bytes!("../web/workspace-tools.js"),
    b"\n;\n",
    include_bytes!("../web/inference.js"),
];

pub(crate) fn viewer(path: &str) -> Option<(&'static str, &'static [u8])> {
    match path {
        "/" | "/index.html" => Some((
            "text/html; charset=utf-8",
            include_bytes!("../web/index.html"),
        )),
        "/inference.js" => Some(("text/javascript", include_bytes!("../web/inference.js"))),
        "/inference-import.js" => Some((
            "text/javascript",
            include_bytes!("../web/inference-import.js"),
        )),
        "/atlas-tools.js" => Some(("text/javascript", include_bytes!("../web/atlas-tools.js"))),
        "/workspace-tools.js" => Some((
            "text/javascript",
            include_bytes!("../web/workspace-tools.js"),
        )),
        "/app.js" => Some(("text/javascript", include_bytes!("../web/app.js"))),
        "/style.css" => Some(("text/css", include_bytes!("../web/style.css"))),
        "/vendor/openseadragon.min.js" => Some((
            "text/javascript",
            include_bytes!("../web/vendor/openseadragon.min.js"),
        )),
        "/vendor/OpenSeadragon-LICENSE.txt" => Some((
            "text/plain",
            include_bytes!("../web/vendor/OpenSeadragon-LICENSE.txt"),
        )),
        _ => None,
    }
}

pub(crate) fn comparison(path: &str) -> Option<(&'static str, &'static [u8])> {
    match path {
        "/" | "/comparison.html" => Some((
            "text/html; charset=utf-8",
            include_bytes!("../web/comparison.html"),
        )),
        "/comparison.js" => Some(("text/javascript", include_bytes!("../web/comparison.js"))),
        "/comparison.css" => Some(("text/css", include_bytes!("../web/comparison.css"))),
        "/vendor/openseadragon.min.js" => Some((
            "text/javascript",
            include_bytes!("../web/vendor/openseadragon.min.js"),
        )),
        "/vendor/OpenSeadragon-LICENSE.txt" => Some((
            "text/plain",
            include_bytes!("../web/vendor/OpenSeadragon-LICENSE.txt"),
        )),
        _ => None,
    }
}

#[cfg(test)]
#[path = "page_asset_tests.rs"]
mod tests;
